### PR TITLE
Add pic to README.md file

### PR DESCRIPTION
**Pull request by belboukayyoub**
Add pic to README.md file

### CODE REVIEW

**Comment by nuuxcode** [comment]
there is no description, please give more details, about this commit, so I can authorize this commit

**Comment by belboukayyoub** [comment]
> There no description, please give more details, about this commit, so I can authorize this commit

If you only open the README.md file you will have all the descriptions you need

**Comment by nuuxcode** [comment]
> > There no description, please give more details, about this commit, so I can authorize this commit
> 
> If you only open the README.md file you will have all the descriptions you need

if you only write a description, I will not have to open README file in another tab and spend another 5 min reading another page, and I will just read the description of the pull request.

so please make a description, so I can finish my review

**Comment by belboukayyoub** [comment]
> > > There no description, please give more details, about this commit, so I can authorize this commit
> > 
> > 
> > If you only open the README.md file you will have all the descriptions you need
> 
> if you only write a description, I will not have to open README file in another tab and spend another 5 min reading another page, and I will just read the description of the pull request.
> 
> so please make a description, so I can finish my review

The main reason  that it's called a review is that you have to check all modifications if you will just read the description you will miss all potential bugs

**Comment by belboukayyoub** [comment]
> > > There no description, please give more details, about this commit, so I can authorize this commit
> > 
> > 
> > If you only open the README.md file you will have all the descriptions you need
> 
> if you only write a description, I will not have to open README file in another tab and spend another 5 min reading another page, and I will just read the description of the pull request.
> 
> so please make a description, so I can finish my review

Because you said that 🤷‍♂️

**Comment by nuuxcode** [comment]
> > > > There no description, please give more details, about this commit, so I can authorize this commit
> > > 
> > > 
> > > If you only open the README.md file you will have all the descriptions you need
> > 
> > 
> > if you only write a description, I will not have to open README file in another tab and spend another 5 min reading another page, and I will just read the description of the pull request.
> > so please make a description, so I can finish my review
> 
> The main reason that it's called a review is that you have to check all modifications if you will just read the description you will miss all potential bugs

why do you assume I only gonna read the description and will not check the files changed, ofc I will, but I wanna know the reason for this commit, what and why, so when I go read the file changed I can know what I'm looking for;

I'm still waiting for the description!! 

one more comment without description, I will close this pull request.

**Comment by nuuxcode** [comment]
> > > > There no description, please give more details, about this commit, so I can authorize this commit
> > > 
> > > 
> > > If you only open the README.md file you will have all the descriptions you need
> > 
> > 
> > if you only write a description, I will not have to open README file in another tab and spend another 5 min reading another page, and I will just read the description of the pull request.
> > so please make a description, so I can finish my review
> 
> Because you said that 🤷‍♂️



> > > > There no description, please give more details, about this commit, so I can authorize this commit
> > > 
> > > 
> > > If you only open the README.md file you will have all the descriptions you need
> > 
> > 
> > if you only write a description, I will not have to open README file in another tab and spend another 5 min reading another page, and I will just read the description of the pull request.
> > so please make a description, so I can finish my review
> 
> Because you said that 🤷‍♂️

what do you mean?

**Comment by nuuxcode** [comment]
make new pull request please with description.

**Comment by nuuxcode** [comment]
Thank you for your contribution to the projects

**Review by nuuxcode — APPROVED** [review]
Good!

**Pull request merged**
